name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  test-lint-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: run tests
      run: npm test

    - name: run eslint
      run: npm run lint:check

    - name: check formatting
      run: npm run format:check

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          mkdir -p /home/deploy/nest-cidi
          

          cd /home/deploy/nest-cidi
          

          if [ -d ".git" ]; then
            git pull origin main
          else
            git clone https://github.com/laflame102/nest-cidi.git .
          fi

          docker compose down || true
          

          docker compose build
          

          docker compose up -d
          

          docker image prune -f